#!/bin/bash
# @day
# Change configs, themes to light
echo "day" >~/.theme_mode

# Kitty
ln -sf ~/themes/kitty/gruvbox_light.conf ~/.config/kitty/themes/current-theme.conf
pkill -USR1 kitty # Tells kitty to reload config

ln -sf ~/themes/taskwarrior/day-theme ~/themes/taskwarrior/current_theme

~/scripts/@/@theme_change_hook
