#!/bin/bash
# @day
# Change configs, themes to light
echo "day" >~/.theme_mode

# Kitty
ln -sf ~/themes/kitty/tomorrow.conf ~/.config/kitty/themes/current-theme.conf
# ln -sf ~/themes/kitty/gruvbox_light.conf ~/.config/kitty/themes/current-theme.conf
pkill -USR1 kitty # Tells kitty to reload config

ln -sf ~/themes/taskwarrior/day-theme ~/themes/taskwarrior/current_theme

# Fish theme -> Light
ln -sf ~/themes/fish/ayu_light.fish ~/themes/fish/current.fish
fish -c 'source ~/themes/fish/current.fish'

~/scripts/@/@theme_change_hook
