#!/bin/bash
# @night
# Change configs, themes to night
echo "night" >~/.theme_mode

# Kitty
ln -sf ~/themes/kitty/gruvbox_dark.conf ~/.config/kitty/themes/current-theme.conf
pkill -USR1 kitty # Tells kitty to reload config

ln -sf ~/themes/taskwarrior/night-theme ~/themes/taskwarrior/current_theme

~/scripts/@/@theme_change_hook
